package git

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"
)

func TestStagedDiffAndCommit(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	setUserConfig(t, repo, "Test", "test@example.com")
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}

	writeFile(t, dir, "hello.txt", "hello\n")
	if _, err := wt.Add("hello.txt"); err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Commit("initial", &gogit.CommitOptions{Author: &object.Signature{Name: "Test", Email: "test@example.com"}}); err != nil {
		t.Fatal(err)
	}

	writeFile(t, dir, "hello.txt", "hello\nworld\n")
	if _, err := wt.Add("hello.txt"); err != nil {
		t.Fatal(err)
	}

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	has, err := HasStagedChanges(opened)
	if err != nil {
		t.Fatal(err)
	}
	if !has {
		t.Fatal("expected staged changes")
	}

	diffs, err := GetStagedDiffs(opened)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffs) != 1 || diffs[0].Path != "hello.txt" || !strings.Contains(diffs[0].Patch, "+world") {
		t.Fatalf("bad diffs: %+v", diffs)
	}

	hash, err := Commit(opened, "feat: update hello")
	if err != nil {
		t.Fatal(err)
	}
	if hash.IsZero() {
		t.Fatal("zero hash")
	}
}

func TestCommitRequiresConfiguredGitUser(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "hello.txt", "hello\n")
	if _, err := wt.Add("hello.txt"); err != nil {
		t.Fatal(err)
	}

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	_, err = Commit(opened, "feat: add hello")
	if err == nil {
		t.Fatal("expected missing user config error")
	}
	if !strings.Contains(err.Error(), "git user.name and user.email") {
		t.Fatalf("error = %v", err)
	}
}

func TestCommitUsesConfiguredGitUser(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	setUserConfig(t, repo, "Real User", "real@example.com")
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "hello.txt", "hello\n")
	if _, err := wt.Add("hello.txt"); err != nil {
		t.Fatal(err)
	}

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	hash, err := Commit(opened, "feat: add hello")
	if err != nil {
		t.Fatal(err)
	}
	commit, err := repo.CommitObject(hash)
	if err != nil {
		t.Fatal(err)
	}
	if commit.Author.Name != "Real User" || commit.Author.Email != "real@example.com" {
		t.Fatalf("author = %+v", commit.Author)
	}
}

func TestFileDiffClassifiesGeneratedAndBinaryFiles(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "gen.go", "// Code generated by tool; DO NOT EDIT.\npackage main\n")
	writeFile(t, dir, "asset.bin", string([]byte{0, 1, 2}))
	if _, err := wt.Add("gen.go"); err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Add("asset.bin"); err != nil {
		t.Fatal(err)
	}

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	diffs, err := GetStagedDiffs(opened)
	if err != nil {
		t.Fatal(err)
	}
	var sawGenerated, sawBinary bool
	for _, fd := range diffs {
		sawGenerated = sawGenerated || (fd.Path == "gen.go" && fd.Generated)
		sawBinary = sawBinary || (fd.Path == "asset.bin" && fd.Binary)
	}
	if !sawGenerated || !sawBinary {
		t.Fatalf("generated=%v binary=%v diffs=%+v", sawGenerated, sawBinary, diffs)
	}
}

func TestUntrackedAndUnstagedFilesAreNotStagedChanges(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "tracked.txt", "initial\n")
	if _, err := wt.Add("tracked.txt"); err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Commit("initial", &gogit.CommitOptions{Author: &object.Signature{Name: "Test", Email: "test@example.com"}}); err != nil {
		t.Fatal(err)
	}

	writeFile(t, dir, "tracked.txt", "modified but unstaged\n")
	writeFile(t, dir, "untracked.txt", "not staged\n")

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	has, err := HasStagedChanges(opened)
	if err != nil {
		t.Fatal(err)
	}
	if has {
		t.Fatal("unstaged and untracked files must not count as staged changes")
	}
	diffs, err := GetStagedDiffs(opened)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffs) != 0 {
		t.Fatalf("expected no staged diffs, got %+v", diffs)
	}
}

func TestGetWorktreeChangesAndStageFiles(t *testing.T) {
	dir := t.TempDir()
	repo, err := gogit.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "tracked.txt", "initial\n")
	if _, err := wt.Add("tracked.txt"); err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Commit("initial", &gogit.CommitOptions{Author: &object.Signature{Name: "Test", Email: "test@example.com"}}); err != nil {
		t.Fatal(err)
	}

	writeFile(t, dir, "tracked.txt", "modified\n")
	writeFile(t, dir, "new.txt", "new\n")

	opened, err := OpenRepository(dir)
	if err != nil {
		t.Fatal(err)
	}
	changes, err := GetWorktreeChanges(opened)
	if err != nil {
		t.Fatal(err)
	}
	if len(changes) != 2 {
		t.Fatalf("changes = %+v", changes)
	}

	if err := StageFiles(opened, []string{"tracked.txt", "new.txt"}); err != nil {
		t.Fatal(err)
	}
	has, err := HasStagedChanges(opened)
	if err != nil {
		t.Fatal(err)
	}
	if !has {
		t.Fatal("expected staged changes after StageFiles")
	}
	diffs, err := GetStagedDiffs(opened)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffs) != 2 {
		t.Fatalf("diffs = %+v", diffs)
	}
}

func setUserConfig(t *testing.T, repo *gogit.Repository, name, email string) {
	t.Helper()
	cfg, err := repo.Config()
	if err != nil {
		t.Fatal(err)
	}
	cfg.User.Name = name
	cfg.User.Email = email
	if err := repo.Storer.SetConfig(cfg); err != nil {
		t.Fatal(err)
	}
}

func writeFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
